name: lidar_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10            
  - pdal
  - gdal
  - shapely
  - pyproj
  - geopandas
  - requests
  - matplotlib
  - rioxarray
  - ipyleaflet
  - notebook
  - jupyterlab
  - pip
